var table = document.getElementById("table-body")
var heading = document.getElementById("title")
var gradeForm = document.querySelector("form")
var pageHeader = new PageHeader(heading)
var gradeTable = new GradeTable(table)
var app = new App(gradeTable, pageHeader, gradeForm)
app.start()
