var table = document.getElementById("table-body")
var heading = document.getElementById("title")
var pageHeader = new PageHeader(heading)
var gradeTable = new GradeTable(table)
var app = new App(gradeTable, pageHeader)
app.start()
