var table = document.getElementById("table-body")
var heading = document.getElementById("title")
var gradeForm = document.querySelector("form")
var noGradesRecorded = document.getElementById("no-grades-recorded")
var newGradeForm = new GradeForm(gradeForm)
var pageHeader = new PageHeader(heading)
var gradeTable = new GradeTable(table, noGradesRecorded)
var app = new App(gradeTable, pageHeader, newGradeForm)
app.start()
